
package GUI;

import EDE.ArregloCliente;
import Clases.Cliente;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOSEPH ROJAS
 */
public class FrmCliente extends javax.swing.JPanel {

    /**
     * Creates new form FrmPropietario
     */
     ArregloCliente datos = new ArregloCliente(10);
    public FrmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrarxd = new javax.swing.JTabbedPane();
        listaPropietario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPropietarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnOrdenar = new javax.swing.JButton();
        registroPropietario = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cboTipodocumento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNdocumento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        cbofecha = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPropietario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPropietarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "T. documento", "F.Nacimiento", "N.documento", "Telefono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(tblPropietarios);
        if (tblPropietarios.getColumnModel().getColumnCount() > 0) {
            tblPropietarios.getColumnModel().getColumn(4).setResizable(false);
        }

        listaPropietario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 671, 257));

        jLabel1.setText("Buscar por:");
        listaPropietario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 66, -1));

        btnRegistrar.setText("Agregar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        listaPropietario.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        listaPropietario.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        listaPropietario.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));
        listaPropietario.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 230, 20));

        btnOrdenar.setText("Ordenar");
        listaPropietario.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        Registrarxd.addTab("Lista", listaPropietario);

        registroPropietario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        registroPropietario.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 237, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        registroPropietario.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 237, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        registroPropietario.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 237, -1, -1));

        jLabel3.setText("Nombre: ");
        registroPropietario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 17, 58, -1));

        jLabel4.setText("Apellido:");
        registroPropietario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 58, -1));

        jLabel5.setText("Tipo documento:");
        registroPropietario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        registroPropietario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 14, 272, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        registroPropietario.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 45, 272, -1));

        cboTipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DNI", "RUC", "PASAPORTE", "CARNÉ DE EXTRANJERÍA  ", "PTP ", "CÉDULA DE IDENTIDAD DE EXTRANJERO ", " " }));
        registroPropietario.add(cboTipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 76, 270, -1));

        jLabel6.setText("Fecha de nacimiento: ");
        registroPropietario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, -1, -1));

        jLabel7.setText("Número de documento:");
        registroPropietario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 134, -1));

        jLabel8.setText("Número de teléfono:");
        registroPropietario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 119, -1));

        jLabel9.setText("Correo electrónico:");
        registroPropietario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 212, 111, -1));

        txtNdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNdocumentoKeyTyped(evt);
            }
        });
        registroPropietario.add(txtNdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 141, 271, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        registroPropietario.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 175, 271, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        registroPropietario.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 209, 271, -1));
        registroPropietario.add(cbofecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 270, -1));

        Registrarxd.addTab("Registro", registroPropietario);

        add(Registrarxd, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Registrarxd.setSelectedComponent(registroPropietario);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        exportar();
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
  // Obtener los textos de los campos
String apellido = txtApellido.getText().trim();
String nombre = txtNombre.getText().trim();
String telefono = txtTelefono.getText().trim();
String correo = txtCorreo.getText().trim();
String nDocumento = txtNdocumento.getText().trim();
String tipoDocumento = (String) cboTipodocumento.getSelectedItem();
String emailRegex = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";

// vserificar que todos los campos estén completos
if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || correo.isEmpty() || nDocumento.isEmpty() || cbofecha.getDate() == null) {
    JOptionPane.showMessageDialog(null, "Completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Detiene la ejecución si hay campos vacíos
}

// verificar la fecha de nacimiento
Date fechaNacimientoDate = cbofecha.getDate();
if (fechaNacimientoDate == null) {
    JOptionPane.showMessageDialog(null, "Seleccione una fecha de nacimiento.", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Detiene la ejecución si no se ha seleccionado una fecha de nacimiento
}

LocalDate fechaNacimiento = fechaNacimientoDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
LocalDate fechaActual = LocalDate.now();
Period periodo = Period.between(fechaNacimiento, fechaActual);

// Verificar la longitud del nombre
if (nombre.length() < 3) {
    JOptionPane.showMessageDialog(null, "El nombre debe tener al menos 3 caracteres.");
    return; // Detiene la ejecución si el nombre es inválido
}

//longitud del apellido
if (apellido.length() < 4) {
    JOptionPane.showMessageDialog(null, "El apellido debe tener al menos 4 caracteres.");
    return; // Detiene la ejecución si el apellido es inválido
}

// Verificar que solo ingresen 9 números exactos
if (telefono.length() != 9) {
    JOptionPane.showMessageDialog(this, "El número de teléfono debe tener exactamente 9 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Verificar formato del correo electrónico
if (!correo.matches(emailRegex)) {
    JOptionPane.showMessageDialog(null, "Ingrese una dirección de correo electrónico válida.", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Detiene la ejecución si el correo electrónico es inválido
}

// Verificar si es mayor de edad
if (periodo.getYears() < 18) {
    JOptionPane.showMessageDialog(null, "No se puede registrar porque es menor de edad.", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Detiene la ejecución si la persona es menor de 18 años
}

// Verificar tipo y número de documento
switch (tipoDocumento) {
    case "DNI":
        if (nDocumento.length() != 8) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de DNI válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        break;
    case "CARNÉ MILITAR Y POLICIAL":
        if (nDocumento.length() != 8) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de Carné Militar y Policial válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        break;
    case "RUC":
        if (nDocumento.length() != 11) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de RUC válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        break;
    case "PASAPORTE":
        if (nDocumento.length() != 20) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de Pasaporte válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        break;
    case "CARNÉ DE EXTRANJERÍA  ":
        if (nDocumento.length() != 20) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de Carnet valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        break;
    case "PTP":
        if (nDocumento.length() != 20) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de PTP valido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        break;
    default:
        JOptionPane.showMessageDialog(this, "Seleccione un tipo de documento válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
}



// Si todas las validaciones pasan, procede con el guardado
agregar();
listar();  // Listar los usuarios después de agregar uno nuevo
Registrarxd.setSelectedComponent(listaPropietario);
JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Registrarxd.setSelectedComponent(listaPropietario);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
     if (txtTelefono.getText().trim().length() == 9) {
            evt.consume();
        }
        char v = evt.getKeyChar();
        if (v < '0' || v > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNdocumentoKeyTyped
           char v = evt.getKeyChar();
        if (v < '0' || v > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtNdocumentoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c  = evt.getKeyChar();
        if((c<'a'||c>'z') && (c<'A')|c>'Z') evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
       char c  = evt.getKeyChar();
        if((c<'a'||c>'z') && (c<'A')|c>'Z') evt.consume();
    }//GEN-LAST:event_txtApellidoKeyTyped

    public static void main(String args[]) {

            FlatCyanLightIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Registrarxd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboTipodocumento;
    private com.toedter.calendar.JDateChooser cbofecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel listaPropietario;
    private javax.swing.JPanel registroPropietario;
    private javax.swing.JTable tblPropietarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNdocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

     private void agregar() {
        // se crea el objeto
        Cliente xd = new Cliente();
        // asignamos los datos
        xd.setNombre(txtNombre.getText());
        xd.setApellido(txtApellido.getText());
        xd.setTipodocumento(cboTipodocumento.getSelectedItem().toString());
        xd.setFechaNacimiento(cbofecha.getDate());
        xd.setNdocumento(txtNdocumento.getText());
        xd.setTelefono(txtTelefono.getText());
        xd.setEmail(txtCorreo.getText());
        // agrega al propietario al arreglo de datos
        datos.agregarPropietario(xd);
        limpiar();
        listar();
    }
    
    private void listar() {
    // Obtener los datos de los propietarios
      Cliente[] aux = datos.getElementos();
      DefaultTableModel dtm = (DefaultTableModel) tblPropietarios.getModel();

      // Limpiar la tabla antes de cargar nuevos datos
      dtm.setRowCount(0);

      SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy"); // Formato de fecha

      for (int i = 0; i < datos.getIndice(); i++) {
          Cliente propietario = aux[i];
          Vector<Object> w = new Vector<>();
          w.add(propietario.getID()); // Agregar el ID
          w.add(propietario.getNombre());
          w.add(propietario.getApellido());
          w.add(propietario.getTipodocumento());

          // Formatear fecha de nacimiento si no es null
          String fechaFormateada = propietario.getFechaNacimiento() != null 
                  ? sdf.format(propietario.getFechaNacimiento()) 
                  : "";
          w.add(fechaFormateada);

          w.add(propietario.getNdocumento());
          w.add(propietario.getTelefono());
          w.add(propietario.getEmail());

          dtm.addRow(w);
      }
    }
    
    
    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        cboTipodocumento.setSelectedIndex(0);
        cbofecha.setDate(null);
        txtNdocumento.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
    }
    private void exportar() {
             try (BufferedWriter bw = new BufferedWriter(new FileWriter("C:\\Users\\JOSEPH ROJAS\\OneDrive\\Documentos\\NetBeansProjects\\Interfaz_de_poo\\src\\Repositorio\\Propietario.txt"))) {

            // Obtener los datos de la tabla
            DefaultTableModel dtm = (DefaultTableModel) tblPropietarios.getModel();
            int filas = dtm.getRowCount();

            // Escribir cada fila de la tabla en el archivo CSV
            for (int i = 0; i < filas; i++) {
                bw.write(dtm.getValueAt(i, 0) + "," + dtm.getValueAt(i, 1) + "," + dtm.getValueAt(i, 2) + "," + dtm.getValueAt(i, 3) + "," + dtm.getValueAt(i, 4) + "," + dtm.getValueAt(i, 5) + "," + dtm.getValueAt(i, 6)+ "," + dtm.getValueAt(i, 7) +"," + "\n");
            }

            JOptionPane.showMessageDialog(this, "Datos exportados correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}
    

    
    
